### ISSUE TITLE
Custom KPI variables

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#508]
Add possibility to use custom variables in the custom KPIs.
(Based on the filtering conditions)

For example: I want to see thread utilization by 2-3-5 statement hashes or i want to get less granularity on the chart (e.g having count(*) > X, where X can be 100 or 10)

**Current situation:** I need to manually adjust yaml file (SQL Script inside of it).
**Proposed idea:** Use bind variable (e.g $var1 $var2) in the custom KPI. When custom KPI will be selected in the Ryba, new pop-up must appear with request to provide variable values.

**Comment by rybafish** [comment]
same as #241
same as #291

**Comment by rybafish** [comment]
- [ ] list of KPIs should be part of custom KPI def
- [ ] dialog for manual adjustment required
- [ ] changes are to be saved into layout

**Comment by rybafish** [comment]
https://www.rybafish.net/variables

**Comment by rybafish** [comment]
give up
