### ISSUE TITLE
Ryba 0.9 Crash (SQL Editor, Change SQL)

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#512]
Hey,

After attempt to put SQL script out of the minichecks scripts, Ryba crashes with the following exception:
2021-11-08 16:04:57 [!] fatal exception
builtins.RuntimeError: wrapped C/C++ object of type QTextLayout has been deleted
>>  File "sqlConsole.py", line 1004, in cursorPositionChanged

Version used: 0.9 beta 5

Steps to reproduce:
1. Connect to the system
2. Take "big" minicheck (my case => HANA_Memory_Overview_2.00.040+)
3. Execute minicheck. Wait for result (I used F9 for execution)
4. Select all in the SQL Editor window (CTRL+A)
5. Paste the content of the same minicheck
6. Ryba will crash.

Rgrds, I.

**Comment by rybafish** [comment]
Seems similar #382

**Comment by rybafish** [comment]
self.cons.selectionChanged.connect(self.selectionChangedS)

TODO:
move everything just inside the cons object

**Comment by rybafish** [comment]
fixed in 09 beta 6
