### ISSUE TITLE
Ryba 0.9 v5 crash (Copy empty result)

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#513]
After request to copy empty result set in the ABAP style, application crashes with the following stack.

2021-11-09 00:21:44 [!] fatal exception

builtins.IndexError: list index out of range

>>  File "sqlConsole.py", line 1474, in contextMenuEvent
>>  File "sqlConsole.py", line 1818, in copyCells

Steps to reproduce:
1. Execute a select which not return any row.
2. Copy the result in the ABAP style.

Use case:
I used this approach to show that there're no backups executed in the system.
I can write "Missing backups" by the words but the proofs have more trust.

**Comment by rybafish** [comment]
self.cons.selectionChanged.connect(self.selectionChangedS)

TODO:
move everything just inside the cons object

**Comment by rybafish** [comment]
fixed in 09 beta 6
