### ISSUE TITLE
Ryba return only 32 rows

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#534]
In case if the result return more than 32798 rows, ryba visualise only 32 rows.

Execute: select **TOP 32798** * from M_LOAD_HISTORY_SERVICE
Query execution time: 22.632 s   (22.632)
**32798 rows fetched**

Execute: select **TOP 32799** * from M_LOAD_HISTORY_SERVICE
Query execution time: 20.816 s   (20.816)
**32 rows fetched**

Issue can be reproduced by execution of the SQLs above.

**Comment by rybafish** [comment]
Same as #181
