### ISSUE TITLE
Extend graph legend

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#569]
Currently graph legend not contain FROM and TO dates but contain MAX aggregate calculated based on the FROM and TO dates.

Add these 2 fields into legend may provide more clean picture about the timeframe used for calculation.
![image](https://user-images.githubusercontent.com/5932285/151000349-1adb1a9d-891b-4a40-b6b0-9be0e9c44251.png)

**Comment by rybafish** [comment]
And what times should be displayed, From-To, or times on the screen?
Seems confusing so far.

**Comment by ShadSpb** [comment]
Screen can be bigger than limits defined from to and max spike can be out of the "visible" area.

From-To must be defined according to the From-To in the graph limits

**Comment by ShadSpb** [comment]
Consider this example:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/5932285/151104466-6d1bb0fc-e12d-4ebd-ac60-6b0eb2f27bc2.png">

THere' max CPU 88% and CPU spike happened at around 19:00
I'm not confident that at 19:00 there was exact this spike, it could happen earlier.

To show some specific moment of time i'm defining proper "border" => TO and FROM times.
It can be few hours, but can be also whole day.
