### ISSUE TITLE
Add markdown formatting

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#685]
If possible, can you please also add MarkDown table formatting to Ryba?
Current ABAP formatting unfortunately not work smoothly with MD. Thank you!

Python library for conversion:
https://pypi.org/project/py-markdown-table/

Markdown tables example:
https://www.markdownguide.org/extended-syntax/
![image](https://user-images.githubusercontent.com/5932285/179538893-3c363711-2d76-48a6-ad5a-29cabc203a07.jpeg)

#Feature

**Comment by ShadSpb** [comment]
Example of HANA output:
| HOST            | PORT      | SERVICE_NAME    | ENTRY_TYPE_NAME          | ESTIMATED_SIZE_GB |
|-----------------|-----------|-----------------|--------------------------|-------------------|
| **spxdh1han0i** | **30003** | **indexserver** | **complete data backup** |    **3862 Gb**    |
| aaaaaaaaaai     | 30003     | indexserver     | differential data backup |      1124 Gb      |
| aaaaaaaaaai    | 30003     | indexserver     |  incremental data backup |      1124 Gb      |
| aaaaaaaaaai     | 30007     | xsengine        |   complete data backup   |        0 Gb       |
| aaaaaaaaaai     | 30007     | xsengine        | differential data backup |        0 Gb       |
| aaaaaaaaaai     | 30007     | xsengine        |  incremental data backup |        0 Gb       |


And PDF export of the similar table:
![image](https://user-images.githubusercontent.com/5932285/179539445-28938137-e83f-499c-bb84-a68758c26c68.jpeg)

**Comment by rybafish** [comment]
It is new normal now.
to disable set copy-markdown: False
