### ISSUE TITLE
Hide Gantt names

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#701]
#Feature #Gantt
With the long-term graphs (days or weeks) gantt entities on the left side of the screen become unreadable and not required anymore.
![image](https://user-images.githubusercontent.com/5932285/184841664-b060c096-0a59-4b50-890b-40790240d637.jpeg)

Add option:
Action => Hide Gantt entity name => Enable / Disable

By disable => Hide Gantt entities from the left part of the screen
By enable => Show Gantt entities on the last part of the screen

Be default => Enabled

If possible, add option to hide bar names without reload.

Thank you, 
regards I.

**Comment by rybafish** [comment]
Right mouse click on the chart --> Hide Gantt Labels?

**Comment by ShadSpb** [comment]
Resolved!
