### ISSUE TITLE
Rotation of the log files (Or cleanup)

### ISSUE THREAD

**Issue by ShadSpb** [rybafish/rybafish#814]
#feature #logs
Sometimes size of the log files may be hundreds of megs.
E.g I have it from 2022
![image](https://user-images.githubusercontent.com/5932285/233072880-38557d87-04ba-485d-9611-da9b0f705fdf.jpeg)
And current size is 208Mb
![image](https://user-images.githubusercontent.com/5932285/233072974-93eda3c6-581a-4a63-b3e1-d90187a4d54b.jpeg)

Most probably, this is due to:
useProfiler: True
loglevel: 5

Parameters.

If possible, can you please think about:
- Possibility to limit file size
[OR]
- Possibility to rotate log files
[OR]
- Cleanup button from application (With startup check about 1st entry and file size)

This not create any type of issue or performance problem. Pure technical improvement.

**Comment by rybafish** [comment]
The default log file limit is 10 MB now: [logSizeMax](https://www.rybafish.net/config#logSizeMax).
