### ISSUE TITLE
Error connecting to hana

### ISSUE THREAD

**Issue by fengjicheng** [rybafish/rybafish#876]
Hello Author：
           click File->connect buttion 
           Fill in the database information and click the connect button
           prompt 
           Connection failed:module 'pyhdb.protocol.constants.function_codes' has no attribute 'COMMIT'

**Comment by rybafish** [comment]
Interesting...

Could you please:
- set loglevel = 5 in the config.yaml 
- restart the tool
- connect again 

and send me the rybafish.log file to rybafishcharts@gmail.com?

thanks

**Comment by fengjicheng** [comment]
Sent, please check it

**Comment by rybafish** [comment]
Seems you are trying to run the version from the code and not the RybaFish.exe build, am I right?

For rybafish to work you will need to use pyhdb fork from [this](https://github.com/rybafish/PyHDB) repository AND merge all the pull requests.

Or just download the build  from rybafish.net

**Comment by fengjicheng** [comment]
YES,
     I run rybafish.py through vscode，I am not using the exe program.Shouldn't   me pip  install PyHDB ?

**Comment by rybafish** [comment]
If you want to run the tool from the code you need to use fork of the pyhdb available [here](https://github.com/rybafish/PyHDB).

You already have standard one installed, it will not work with RybaFish due to several limitations.

Please checkout the fork version and make sure it is imported before the standard one.

**Comment by fengjicheng** [comment]
Thank you.
               I found your forked from SAP archive/PyHDB.
               I solved it by modifying your code.

**Comment by rybafish** [comment]
Glad it worked, let me know in case questions.

Closing the issue
